//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YF_Brad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIP
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public string JurisName { get; set; }
        public int HealthDistrictsId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual HealthDistrict HealthDistrict { get; set; }
    }
}
